### ISSUE TITLE
Document why

### ISSUE THREAD

**Issue by jacobrosenthal** [korken89/rust-embedded-example-project#2]
Im trying to remember which issues specifically to watch for when this style setup won't be necessary.

Does std aware cargo get us out of this?
https://github.com/rust-lang/wg-cargo-std-aware/issues/9

Or 5730?
https://github.com/rust-lang/cargo/issues/5730

Thanks for the template!

**Comment by korken89** [comment]
Hi thanks for the issue!

The main issue is that we define a panic handler in the binary, which causes most of everything to break if you want to test. However when using this template the firmware crate is just no_std and does not have the issue.

Might be more as well, I figured out this approach when I started with embedded Rust and didn't really take the time to look back and see what is the status of issues today.
Plus, with this approach one can always switch out MCU without much extra work if that is important :)
